### ISSUE TITLE
What is the rational behind pkg_path_filename in get_datafile()?

### ISSUE THREAD

**Issue by asafkahlon** [DropD/reentry#36]
Hi :)
First of all, thanks for a great package!

I would like to know if the name of the filename created in get_datafile function (config.py) has some important meaning and weather of not it can be changed.

This name can be a little problematic when compiling code for embedded systems, since you compile with one python interpreter on your host, but use another one on your target. Therefore, the name of the file created during compilation won't match the name that will be checked when trying to traverse the registered entry points on the board.

For example, if you compile with Buildroot, the python executable you use will probably reside at something like /home/user/buildroot/output/host/bin/python. This will lead to a configuration file with the name home.user.buildroot.output.host.bin.python. But on the board itself your python interpreter would probably be just "/usr/bin/python" and hence reentry will look for usr.bin.python, which of course won't be found.

I think this package can be very useful, especially on embedded systems, in which you will more likely to have limited resources.
I already tried to rename the file created with Buildroot after the compilation and use it on a board, and everything seems to look fine.

Thanks!

**Comment by DropD** [comment]
The reason the cache file is named for the interpreter is to make it possible to use the same package with a different set of plugins in separate python environments on the same machine.

This can not be solved by placing the cache file relative to the package install location because the user might not have write permissions there.

I can see some ways to allow for your use case, possibly with an override in the config file. What do you think? and would you be interested in implementing a fix?

**Comment by ltalirz** [comment]
Closing this since the question has been addressed - happy to reopen in case there is renewed interest to work on this.

**Comment by asafkahlon** [comment]
Hi.
If needed I can implement the feature.
@DropD can you please elaborate in more detail what exactly is the change which solves this issue?

**Comment by ltalirz** [comment]
@asafkahlon Thanks for offering your help!
I believe, the suggestion is to add a field in the config file in order to set the filename.

So far, the config file (which we should document now!) only has a single function: to specify the location of the data files. E.g. you can create a file `~/.config/reentry/config` with contents
```
[general]
datadir=/Users/leopold/mydir
```
to change where reentry stores the data (see `config.py` for details).

The idea would be to add another field for configuring the name of the config file (not sure what exactly you would like, whether it's to hardcode the exact name etc.).

You will notice that there are currently two functions for getting the file name - I think it's time to get rid of the first one in favor of the second one
https://github.com/DropD/reentry/blob/06cabf7841d1fdb78d68cbd8395598d16d8ab286/reentry/config.py#L66-L92

**Comment by asafkahlon** [comment]
Sounds like a plan :)
Would it be fine if I also add an option to set the filename with an environment variable (similar to what the package already supports with the datadir)?

**Comment by ltalirz** [comment]
> Would it be fine if I also add an option to set the filename with an environment variable (similar to what the package already supports with the datadir)?

fine with me!
