### ISSUE TITLE
Tests fail with pip>=19

### ISSUE THREAD

**Issue by DropD** [DropD/reentry#44]
Something must have changed in pip / setuptools which does not allow reentry to use `pkg_resources.get_distribution` on the distribution being currently installed anymore. This prevents the scan hook from working.

**Comment by ltalirz** [comment]
While investigating the issue, I noticed that the `reentry_register` hook actually seems to be working just fine - I believe this is because it is using the `dist` argument that it is being passed *directly*.

The `reentry_scan` hook doesn't use the `dist` argument - rather, it uses the `value` it is passed (a list of group names) and then scans for those.
It seems there is some inconsistency in `pkg_resources`. The scan involves walking over all available distributions:
https://github.com/DropD/reentry/blob/1d17bfdc00b7824980783f9a825cb202d28c281f/reentry/default_manager.py#L93-L95
For some reason, the *installing* distribution (e.g. `reentry-test-host`) seems to already be part of this list, but the following translation from a dist name into a dist fails:
https://github.com/DropD/reentry/blob/1d17bfdc00b7824980783f9a825cb202d28c281f/reentry/abcbackend.py#L98-L102

However, if I understand correctly, this translation is actually not necessary, since the entry points of the installing distribution will already have been registered (if `reentry_register: True`). So, we could just ignore this with a `try/except`.

**Comment by ltalirz** [comment]
@DropD I think most of the issues are resolved - there is one, however, that I don't see how to resolve:

When the `reentry_scan` hook is triggered, it turns out that `pkg_resources.AvailableDistributions()` only provides access to the distributions installed in the build environment (setuptools, wheel, click...). That kind of defeats the purpose of the hook.

So, I'm wondering: is this hook really needed?
As far as I understand, it is only really needed when some plugin "forgets" to `reentry_register`.
Is that correct or are there other use cases?
If not, I would suggest we drop the `reentry_scan` hook, considering also that it doesn't always work (e.g. if the "forgetful" plugin is installed in the same pip command).
